"use strict";

module.exports = function (sequelize, DataTypes) {
  var View = sequelize.define("vwh_follow_up", {
    id: { type: DataTypes.INTEGER, primaryKey: true },
    code: { type: DataTypes.STRING },
    posId: { type: DataTypes.INTEGER },
    storeId: { type: DataTypes.INTEGER },
    storeCode: { type: DataTypes.STRING },
    storeName: { type: DataTypes.STRING },
    cashierTransId: { type: DataTypes.INTEGER },
    cashierId: { type: DataTypes.STRING },
    cashierName: { type: DataTypes.STRING },
    birthDate: { type: DataTypes.DATE },
    cityId: { type: DataTypes.INTEGER },
    cityName: { type: DataTypes.STRING },
    address01: { type: DataTypes.STRING },
    address02: { type: DataTypes.STRING },
    technicianId: { type: DataTypes.INTEGER },
    technicianCode: { type: DataTypes.STRING },
    technicianName: { type: DataTypes.STRING },
    memberId: { type: DataTypes.INTEGER },
    memberCode: { type: DataTypes.STRING },
    memberName: { type: DataTypes.STRING },
    mobileNumber: { type: DataTypes.STRING },
    phoneNumber: { type: DataTypes.STRING },
    gender: { type: DataTypes.STRING },
    policeNo: { type: DataTypes.STRING },
    policeNoId: { type: DataTypes.INTEGER },
    lastMeter: { type: DataTypes.INTEGER },
    transNoId: { type: DataTypes.INTEGER },
    transNo: { type: DataTypes.STRING },
    transDate: { type: DataTypes.DATE },
    transTime: { type: DataTypes.DATE },
    transNoStatus: { type: DataTypes.STRING },
    dpp: { type: DataTypes.NUMERIC },
    ppn: { type: DataTypes.NUMERIC },
    nettoTotal: { type: DataTypes.NUMERIC },
    status: { type: DataTypes.STRING },
    lastCaller: { type: DataTypes.STRING },
    lastCall: { type: DataTypes.DATE },
    customerSatisfaction: { type: DataTypes.STRING },
    postService: { type: DataTypes.DATE },
    nextCall: { type: DataTypes.DATE },
    pendingReason: { type: DataTypes.STRING },
    denyOfferingReason: { type: DataTypes.STRING },
    acceptOfferingDate: { type: DataTypes.DATE },
    acceptOfferingReason: { type: DataTypes.STRING },
    createdBy: { type: DataTypes.STRING },
    createdAt: { type: DataTypes.DATE },
    updatedBy: { type: DataTypes.STRING },
    updatedAt: { type: DataTypes.DATE }
  }, { tableName: 'vwh_follow_up' })
  return View
}
