"use strict";

module.exports = function (sequelize, DataTypes) {
  return sequelize.define("vw_stock_list", {
    storeid: { type: DataTypes.INTEGER, primaryKey: true },
    storecode: { type: DataTypes.STRING },
    storename: { type: DataTypes.STRING },
    productid: { type: DataTypes.INTEGER },
    productcode: { type: DataTypes.STRING },
    productname: { type: DataTypes.STRING },
    brandid: { type: DataTypes.INTEGER },
    brandname: { type: DataTypes.STRING },
    categoryid: { type: DataTypes.INTEGER },
    categorycode: { type: DataTypes.STRING },
    categoryname: { type: DataTypes.STRING },
    shelf: { type: DataTypes.STRING },
    qtystock: { type: DataTypes.NUMERIC },
    qtypartition: { type: DataTypes.NUMERIC },
    qtyonhand: { type: DataTypes.NUMERIC },
    costprice: { type: DataTypes.NUMERIC },
    costpricelocal: { type: DataTypes.NUMERIC },
    costpriceglobal: { type: DataTypes.NUMERIC },
    sellprice: { type: DataTypes.NUMERIC },
    sellpricelocal: { type: DataTypes.NUMERIC },
    sellpriceglobal: { type: DataTypes.NUMERIC },
    distprice01: { type: DataTypes.NUMERIC },
    distprice01local: { type: DataTypes.NUMERIC },
    distprice01global: { type: DataTypes.NUMERIC },
    distprice02: { type: DataTypes.NUMERIC },
    distprice02local: { type: DataTypes.NUMERIC },
    distprice02global: { type: DataTypes.NUMERIC },
    curr_hpp: { type: DataTypes.NUMERIC },
    use_warranty: { type: DataTypes.BOOLEAN },
    valid_warranty_km: { type: DataTypes.NUMERIC },
    valid_warranty_period: { type: DataTypes.INTEGER },
  }, { tableName: 'vw_stock_list', freezeTableName: true })
}